<?php
/**
 * Created by PhpStorm.
 * User: Matt
 * Date: 1/27/2016
 * Time: 5:34 AM
 */
/**
 *  Implements hook_menu().
 */
function commerce_options_extras_menu() {
  $items = array();

  return $items;
}

/**
 *  Implements hook_views_api().
 */
function commerce_options_extras_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_options_extras') . '/views',
  );

}